# Generated by Django 3.2.19 on 2023-05-10 14:44

import ckeditor_uploader.fields
from django.db import migrations, models
import garpix_notify.utils.file
import garpix_notify.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifytemplate',
            name='html_from_type',
            field=models.TextField(choices=[('ckeditor', 'Визуальный редактор'), ('zipfile', 'Загрузка из архива')], default='ckeditor', max_length=8, verbose_name='Способ формирования html'),
        ),
        migrations.AddField(
            model_name='notifytemplate',
            name='zipfile',
            field=models.FileField(blank=True, help_text='Поддерживаются архивы в форматах ZIP и RAR с единственным HTML-файлом и ассетами изображений по относительному или абсолютному пути', null=True, upload_to=garpix_notify.utils.file.get_file_path, validators=[garpix_notify.utils.validators.validate_zip], verbose_name='Файл архива'),
        ),
        migrations.AddField(
            model_name='systemnotify',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='html',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='HTML'),
        ),
    ]
