# Generated by Django 3.2.19 on 2023-05-10 14:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20221115_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date email was confirmed'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date phone was confirmed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_code_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправления кода'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код подтверждения email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=True, verbose_name='Email подтвержден'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_phone_confirmed',
            field=models.BooleanField(default=True, verbose_name='Номер телефона подтвержден'),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Новый email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Новый номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_code_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправления кода'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_confirmation_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Код подтверждения номера телефона'),
        ),
    ]
