# Generated by Django 3.2.19 on 2023-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Полный URL страницы'),
        ),
    ]
