# Generated by Django 3.2.16 on 2022-11-14 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0001_initial'),
        ('garpix_cart', '0002_auto_20221115_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_user.usersession', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
